print("Hoe is het om hier te wonen?")
print("A. Het is een leuke omgeving om te wonen.")
print("B. Het is oke om hier te wonen.")
print("C. Ik haat het om hier te wonen.")
antwoord = input("")
print("Hoe zijn de mensen in Nederland tegen vluchtelingen?")
print("A. Over het algemeen reageren de mensen er niet slecht tegen.")
print("B. Het ligt er echt aan waar je woont.")
print("C. De meeste mensen zijn discriminerend of racistisch.")
antwoord = input("")
print("Zijn de huizen stabiel om in te leven?")
print("A. Ja.")
print("B. Nee.")
print("C. ik weet het niet.")
antwoord = input("")